[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rayfos"
version = "1.0.0"
description = "tool"
dependencies = []

[pytest]
pythonpath = "repo/rayfos"

[tool.pytest.ini_options]
python_files = "*_test.py"
