# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rayfos
email: rayfos.fun@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  以遊戲方式呈現的部落格。
  A blog representing in games.
baseurl: "/gblog" # the subpath of your site, e.g. /blog
url: "http://rayfos-fun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rayfos-fun

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  games-en:
    output: true
  games-zh-cn:
    output: true
  games-zh-tw:
    output: true
  others-en:
    output: true
  others-zh-cn:
    output: true
  others-zh-tw:
    output: true
  stories-en:
    output: true
  stories-zh-cn:
    output: true
  stories-zh-tw:
    output: true
  tools-en:
    output: true
  tools-zh-cn:
    output: true
  tools-zh-tw:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
